# This is a basic workflow to help you get started with Actions

name: Build Docker Images CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        jdkversion: [11, 16, 17]
        baseimage: ["cbld", "mariner", "ubuntu"]

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the image
        run: docker build -t mcr.microsoft.com/openjdk/jdk:${{ matrix.jdkversion }}-${{ matrix.baseimage }} -f ./docker/${{ matrix.baseimage }}/Dockerfile.msopenjdk-${{ matrix.jdkversion }}-jdk ./docker/${{ matrix.baseimage }}/

  validate_images:
    runs-on: ubuntu-latest
    steps:
      # Validate the images
      - name: Validate container images
        run: ./validate-docker-images.sh 
