name: Check JDK Versions on Published MCR Images CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run the validate-docker-images.sh script
        run: ./validate-docker-images.sh

      # Tests other versions of Ubuntu
      - name: Run test-ubuntu.sh script
        run: ./test-ubuntu.sh
