name: Check JDK Versions on Published MCR Images CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate container images
        run: ./validate-docker-images.sh
