name: Validate Published Images

on:
  workflow_dispatch:

jobs:

  build_temurin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distros: [ "mariner", "distroless" ]
        jdkvendor: [ "temurin" ]
        jdkversion: [ { major: "8", expected: "1.8.0_332" } ]
    steps:
      - uses: actions/checkout@v2

      - name: Validate container images
        run: |
          ./validate-image.sh ${{ matrix.distros }} ${{ matrix.jdkvendor }} ${{ matrix.jdkversion.major }} ${{ matrix.jdkversion.expected }} 
